-- An employee the assistant invented from a report is not the same thing as an
-- employee somebody configured, and the difference matters: the invented one
-- carries a department guessed from whichever report it first appeared in, and
-- that guess then influences how later rows are filed.
--
-- Without this column a purge cannot tell them apart, so demo-derived people
-- survive a reset and quietly mis-file real reports afterwards.
alter table employees add column if not exists auto_created boolean not null default false;

-- Every employee whose id was generated by the importer rather than configured.
-- Seeded ids are EMP-001..EMP-010; generated ids are EMP- plus a hex hash.
update employees set auto_created = true
 where auto_created = false
   and employee_id ~ '^EMP-[0-9A-F]{6}$';
